eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health

spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.251:1521:ORCL
    username: CACSCH
    password: CACSCH
    driver-class-name: oracle.jdbc.OracleDriver    
    
server:
  port: 1235 