eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    status-page-url-path: /infoAlumno
    health-check-url-path: /healthAlumno
      

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicio?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: c00p3r4t1v4
    
server:
  port: 1234 